///*
// * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
// * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
// */
//package org.example.view.CommonView;
//
///**
// *
// * @author admin
// */
//public class ForgotPasswordView extends javax.swing.JFrame {
//
//    /**
//     * Creates new form ForgotPasswordView
//     */
//    public ForgotPasswordView() {
//        initComponents();
//        this.setLocationRelativeTo(null);
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated
//    // Code">//GEN-BEGIN:initComponents
//    private void initComponents() {
//
//        Right = new javax.swing.JPanel();
//        jLabel1 = new javax.swing.JLabel();
//        jLabel4 = new javax.swing.JLabel();
//        jLabel2 = new javax.swing.JLabel();
//        resetButton = new javax.swing.JButton();
//        txtEmailReset = new javax.swing.JTextField();
//        btnBack = new javax.swing.JButton();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        Right.setBackground(new java.awt.Color(102, 0, 102));
//        Right.setForeground(new java.awt.Color(255, 153, 0));
//        Right.setPreferredSize(new java.awt.Dimension(800, 500));
//
//        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RES1/Warehouse_Manager_logo.png"))); // NOI18N
//
//        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
//        jLabel4.setText("Copyright © warehouse manager company All rights reversed");
//
//        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
//        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
//        jLabel2.setText("Email");
//
//        resetButton.setBackground(new java.awt.Color(255, 153, 0));
//        resetButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
//        resetButton.setText("RESET PASSWORD");
//        resetButton.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                resetButtonActionPerformed(evt);
//            }
//        });
//
//        txtEmailReset.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                txtEmailResetActionPerformed(evt);
//            }
//        });
//
//        btnBack.setBackground(new java.awt.Color(255, 153, 0));
//        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
//        btnBack.setText("Back");
//        btnBack.setPreferredSize(new java.awt.Dimension(157, 27));
//        btnBack.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnBackActionPerformed(evt);
//            }
//        });
//
//        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
//        Right.setLayout(RightLayout);
//        RightLayout.setHorizontalGroup(
//                RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(RightLayout.createSequentialGroup()
//                                .addComponent(jLabel1)
//                                .addGap(0, 0, Short.MAX_VALUE))
//                        .addGroup(RightLayout.createSequentialGroup()
//                                .addGroup(RightLayout
//                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
//                                        .addGroup(RightLayout
//                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                                .addGroup(RightLayout.createSequentialGroup()
//                                                        .addGap(157, 157, 157)
//                                                        .addComponent(jLabel2)
//                                                        .addPreferredGap(
//                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                                        .addComponent(txtEmailReset,
//                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 318,
//                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
//                                                .addGroup(RightLayout.createSequentialGroup()
//                                                        .addGap(290, 290, 290)
//                                                        .addComponent(resetButton)))
//                                        .addGroup(RightLayout.createSequentialGroup()
//                                                .addGap(23, 23, 23)
//                                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 87,
//                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
//                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                                .addComponent(jLabel4)))
//                                .addContainerGap(218, Short.MAX_VALUE)));
//        RightLayout.setVerticalGroup(
//                RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(RightLayout.createSequentialGroup()
//                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118,
//                                        javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(86, 86, 86)
//                                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jLabel2)
//                                        .addComponent(txtEmailReset, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
//                                                javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(18, 18, 18)
//                                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
//                                        javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120,
//                                        Short.MAX_VALUE)
//                                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jLabel4)
//                                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
//                                                javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(41, 41, 41)));
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addComponent(Right, javax.swing.GroupLayout.Alignment.TRAILING,
//                                javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE));
//        layout.setVerticalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addComponent(Right, javax.swing.GroupLayout.PREFERRED_SIZE,
//                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));
//
//        pack();
//    }// </editor-fold>//GEN-END:initComponents
//
//    private void txtEmailResetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtEmailResetActionPerformed
//        // TODO add your handling code here:
//    }// GEN-LAST:event_txtEmailResetActionPerformed
//
//    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_resetButtonActionPerformed
//        // TODO add your handling code here:
//    }// GEN-LAST:event_resetButtonActionPerformed
//
//    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBackActionPerformed
//        // TODO add your handling code here:
//        LoginView loginView = new LoginView();
//        loginView.setVisible(true);
//        this.dispose();
//    }// GEN-LAST:event_btnBackActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
//        // (optional) ">
//        /*
//         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
//         * look and feel.
//         * For details see
//         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ForgotPasswordView.class.getName()).log(java.util.logging.Level.SEVERE,
//                    null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ForgotPasswordView.class.getName()).log(java.util.logging.Level.SEVERE,
//                    null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ForgotPasswordView.class.getName()).log(java.util.logging.Level.SEVERE,
//                    null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ForgotPasswordView.class.getName()).log(java.util.logging.Level.SEVERE,
//                    null, ex);
//        }
//        // </editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ForgotPasswordView().setVisible(true);
//            }
//        });
//    }
//
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JPanel Right;
//    private javax.swing.JButton btnBack;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JLabel jLabel4;
//    private javax.swing.JButton resetButton;
//    private javax.swing.JTextField txtEmailReset;
//    // End of variables declaration//GEN-END:variables
//}
