///*
// * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
// * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
// */
//package org.example.view.CommonView;
//
//import java.util.Arrays;
//import javax.swing.JOptionPane;
//
//import org.example.domain.DTO.Request.LoginRequest;
//import org.example.domain.DTO.Response.LoginResponse;
//import org.example.domain.model.UserModel;
//import org.example.repository.UserDAO;
//import org.example.service.user.UserService;
//import org.example.service.user.IMPL.UserServiceImpl;
//import org.example.view.AdminView.AdminDashboardView;
//import org.example.view.UserView.UserDashboard;
//
///**
// *
// * @author admin
// */
//public class LoginView extends javax.swing.JFrame {
//    private UserService userService;
//
//    /**
//     * Creates new form LoginView
//     */
//    public LoginView() {
//        initComponents();
//        this.setLocationRelativeTo(null);
//        UserDAO userDAO = new UserDAO();
//        this.userService = new UserServiceImpl(userDAO);
//    }
//
//    private void validateInput() {
//        if (txtUsernameLogin.getText().isEmpty()
//                || Arrays.toString(txtPassword.getPassword()).isEmpty()) {
//            JOptionPane.showMessageDialog(this, "All fields are required");
//            throw new IllegalArgumentException("All fields are required");
//        }
//    }
//
////    public void loginSuccess(UserModel user) {
////        SessionManager.setCurrentUser(user);
////    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated
//    // <editor-fold defaultstate="collapsed" desc="Generated
//    // <editor-fold defaultstate="collapsed" desc="Generated
//    // <editor-fold defaultstate="collapsed" desc="Generated
//    // Code">//GEN-BEGIN:initComponents
//    private void initComponents() {
//
//        jPanel1 = new javax.swing.JPanel();
//        Right = new javax.swing.JPanel();
//        jLabel1 = new javax.swing.JLabel();
//        jLabel2 = new javax.swing.JLabel();
//        jLabel3 = new javax.swing.JLabel();
//        jLabel4 = new javax.swing.JLabel();
//        Left = new javax.swing.JPanel();
//        jLabel5 = new javax.swing.JLabel();
//        jLabel6 = new javax.swing.JLabel();
//        txtUsernameLogin = new javax.swing.JTextField();
//        jLabel7 = new javax.swing.JLabel();
//        btnSignup = new javax.swing.JButton();
//        jLabel8 = new javax.swing.JLabel();
//        btnLogin = new javax.swing.JButton();
//        txtPassword = new javax.swing.JPasswordField();
//        showPasswordCheckbox = new javax.swing.JCheckBox();
//        forgotPasswordButton = new javax.swing.JButton();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//        setTitle("LOGIN");
//
//        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
//        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
//        jPanel1.setLayout(null);
//
//        Right.setBackground(new java.awt.Color(102, 0, 102));
//        Right.setForeground(new java.awt.Color(255, 153, 0));
//
//        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RES1/Warehouse_Manager_logo.png"))); // NOI18N
//
//        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
//        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
//        jLabel2.setText("We make inventory simple, ");
//
//        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
//        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
//        jLabel3.setText("you can focus on growing your business.");
//
//        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
//        jLabel4.setText("Copyright © warehouse manager company All rights reversed");
//
//        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
//        Right.setLayout(RightLayout);
//        RightLayout.setHorizontalGroup(
//                RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(RightLayout.createSequentialGroup()
//                                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(RightLayout
//                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                                .addGroup(RightLayout.createSequentialGroup()
//                                                        .addGap(28, 28, 28)
//                                                        .addComponent(jLabel4)
//                                                        .addGap(36, 36, 36))
//                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
//                                                        RightLayout.createSequentialGroup()
//                                                                .addContainerGap()
//                                                                .addComponent(jLabel1)))
//                                        .addGroup(RightLayout.createSequentialGroup()
//                                                .addContainerGap()
//                                                .addGroup(RightLayout
//                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                                        .addComponent(jLabel3)
//                                                        .addGroup(RightLayout.createSequentialGroup()
//                                                                .addGap(45, 45, 45)
//                                                                .addComponent(jLabel2)))))
//                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
//        RightLayout.setVerticalGroup(
//                RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(RightLayout.createSequentialGroup()
//                                .addGap(36, 36, 36)
//                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118,
//                                        javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(41, 41, 41)
//                                .addComponent(jLabel2)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addComponent(jLabel3)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146,
//                                        Short.MAX_VALUE)
//                                .addComponent(jLabel4)
//                                .addGap(103, 103, 103)));
//
//        jPanel1.add(Right);
//        Right.setBounds(0, 0, 390, 520);
//        Right.getAccessibleContext().setAccessibleParent(this);
//
//        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 45)); // NOI18N
//        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
//        jLabel5.setText("LOGIN");
//
//        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
//        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
//        jLabel6.setText("Username");
//
//        txtUsernameLogin.setBackground(new java.awt.Color(153, 0, 153));
//        txtUsernameLogin.setForeground(new java.awt.Color(255, 255, 255));
//        txtUsernameLogin.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                txtUsernameLoginActionPerformed(evt);
//            }
//        });
//
//        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
//        jLabel7.setForeground(new java.awt.Color(102, 0, 102));
//        jLabel7.setText("Password");
//
//        btnSignup.setBackground(new java.awt.Color(102, 0, 102));
//        btnSignup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
//        btnSignup.setForeground(new java.awt.Color(255, 255, 255));
//        btnSignup.setText("SIGN UP");
//        btnSignup.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnSignupActionPerformed(evt);
//            }
//        });
//
//        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
//        jLabel8.setForeground(new java.awt.Color(102, 0, 102));
//        jLabel8.setText("If you don't have an account");
//
//        btnLogin.setBackground(new java.awt.Color(102, 0, 102));
//        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
//        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
//        btnLogin.setText("LOGIN");
//        btnLogin.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnLoginActionPerformed(evt);
//            }
//        });
//
//        txtPassword.setBackground(new java.awt.Color(153, 0, 153));
//        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
//        txtPassword.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                txtPasswordActionPerformed(evt);
//            }
//        });
//
//        showPasswordCheckbox.setForeground(new java.awt.Color(102, 0, 102));
//        showPasswordCheckbox.setText("Show password");
//        showPasswordCheckbox.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                showPasswordCheckboxActionPerformed(evt);
//            }
//        });
//
//        forgotPasswordButton.setForeground(new java.awt.Color(102, 0, 102));
//        forgotPasswordButton.setText("Forgot your password?");
//        forgotPasswordButton.setBorder(null);
//        forgotPasswordButton.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                forgotPasswordButtonActionPerformed(evt);
//            }
//        });
//
//        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
//        Left.setLayout(LeftLayout);
//        LeftLayout.setHorizontalGroup(
//                LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(LeftLayout.createSequentialGroup()
//                                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(LeftLayout.createSequentialGroup()
//                                                .addGap(125, 125, 125)
//                                                .addComponent(jLabel5))
//                                        .addGroup(LeftLayout.createSequentialGroup()
//                                                .addGap(31, 31, 31)
//                                                .addGroup(LeftLayout
//                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
//                                                                false)
//                                                        .addGroup(LeftLayout.createSequentialGroup()
//                                                                .addComponent(showPasswordCheckbox)
//                                                                .addPreferredGap(
//                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
//                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
//                                                                        Short.MAX_VALUE)
//                                                                .addComponent(forgotPasswordButton,
//                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 137,
//                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
//                                                        .addComponent(txtUsernameLogin)
//                                                        .addComponent(jLabel6)
//                                                        .addComponent(jLabel7)
//                                                        .addComponent(txtPassword)
//                                                        .addGroup(LeftLayout.createSequentialGroup()
//                                                                .addGap(2, 2, 2)
//                                                                .addGroup(LeftLayout.createParallelGroup(
//                                                                        javax.swing.GroupLayout.Alignment.LEADING)
//                                                                        .addComponent(btnLogin,
//                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
//                                                                                116,
//                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                                        .addGroup(LeftLayout.createSequentialGroup()
//                                                                                .addComponent(jLabel8)
//                                                                                .addGap(11, 11, 11)
//                                                                                .addComponent(btnSignup,
//                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
//                                                                                        116,
//                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))))))
//                                .addContainerGap(84, Short.MAX_VALUE)));
//        LeftLayout.setVerticalGroup(
//                LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(LeftLayout.createSequentialGroup()
//                                .addGap(40, 40, 40)
//                                .addComponent(jLabel5)
//                                .addGap(29, 29, 29)
//                                .addComponent(jLabel6)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addComponent(txtUsernameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
//                                        javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(18, 18, 18)
//                                .addComponent(jLabel7)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
//                                        javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(showPasswordCheckbox)
//                                        .addComponent(forgotPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
//                                                javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(26, 26, 26)
//                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
//                                        javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jLabel8)
//                                        .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
//                                                javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addContainerGap(84, Short.MAX_VALUE)));
//
//        jPanel1.add(Left);
//        Left.setBounds(390, 0, 440, 520);
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
//                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
//        layout.setVerticalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
//                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
//
//        pack();
//    }// </editor-fold>//GEN-END:initComponents
//
//    private void txtUsernameLoginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtEmailLoginActionPerformed
//        // TODO add your handling code here:
//    }// GEN-LAST:event_txtEmailLoginActionPerformed
//
//    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSignupActionPerformed
//        // TODO add your handling code here:
//        RegisterView registerView = new RegisterView();
//        registerView.setVisible(true);
//        this.dispose();
//    }// GEN-LAST:event_btnSignupActionPerformed
//
//    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLoginActionPerformed
//        // TODO add your handling code here:
//        validateInput();
//        try {
//            LoginRequest loginRequest = new LoginRequest(
//                    txtUsernameLogin.getText().trim(),
//                    new String(txtPassword.getPassword()).trim());
//
//            AuthController authController = new AuthController();
//            LoginResponse response = authController.login(loginRequest);
//
//            if (response == null || response.getRole() == null) {
//                JOptionPane.showMessageDialog(this, "Invalid login response", "Login Error", JOptionPane.ERROR_MESSAGE);
//                return;
//            }
//
//            loginSuccess(response.getUser());
//
//            switch (response.getRole().toUpperCase()) {
//                case "ADMIN":
//                    JOptionPane.showMessageDialog(this, "Login successful - Welcome Admin");
//                    AdminDashboardView adminView = new AdminDashboardView();
//                    adminView.setVisible(true);
//                    this.dispose();
//                    break;
//
//                case "USER":
//
//                    JOptionPane.showMessageDialog(this, "Login successful - Welcome User");
//                    UserDashboard userView = new UserDashboard();
//                    userView.setVisible(true);
//                    this.dispose();
//                    break;
//
//                default:
//                    JOptionPane.showMessageDialog(this, "Unknown user role: " + response.getRole(),
//                            "Login Error",
//                            JOptionPane.ERROR_MESSAGE);
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "Login failed: " + e.getMessage(), "Error: ",
//                    JOptionPane.ERROR_MESSAGE);
//        }
//
//    }// GEN-LAST:event_btnLoginActionPerformed
//
//    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtPasswordActionPerformed
//        // TODO add your handling code here:
//    }// GEN-LAST:event_txtPasswordActionPerformed
//
//    private void showPasswordCheckboxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_showPasswordCheckboxActionPerformed
//        // TODO add your handling code here:
//        if (showPasswordCheckbox.isSelected()) {
//            txtPassword.setEchoChar((char) 0);
//        } else {
//            txtPassword.setEchoChar('*');
//        }
//    }// GEN-LAST:event_showPasswordCheckboxActionPerformed
//
//    private void forgotPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_forgotPasswordButtonActionPerformed
//        // TODO add your handling code here:
//        ForgotPasswordView forgotPasswordView = new ForgotPasswordView();
//        forgotPasswordView.setVisible(true);
//        this.dispose();
//    }// GEN-LAST:event_forgotPasswordButtonActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
//        // (optional) ">
//        /*
//         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
//         * look and feel.
//         * For details see
//         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        // </editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoginView().setVisible(true);
//            }
//        });
//    }
//
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JPanel Left;
//    private javax.swing.JPanel Right;
//    private javax.swing.JButton btnLogin;
//    private javax.swing.JButton btnSignup;
//    private javax.swing.JButton forgotPasswordButton;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JLabel jLabel3;
//    private javax.swing.JLabel jLabel4;
//    private javax.swing.JLabel jLabel5;
//    private javax.swing.JLabel jLabel6;
//    private javax.swing.JLabel jLabel7;
//    private javax.swing.JLabel jLabel8;
//    private javax.swing.JPanel jPanel1;
//    private javax.swing.JCheckBox showPasswordCheckbox;
//    private javax.swing.JPasswordField txtPassword;
//    private javax.swing.JTextField txtUsernameLogin;
//    // End of variables declaration//GEN-END:variables
//}
